site_name: SMC Platform Design
pages:
    - Home: index.md
    - Terminology and Concepts: terminology-and-concepts.md
    - Config and Message Formats: json-formats.md
    - Currently Supported Signals and Properties: signals-and-properties.md
theme: readthedocs
